### PR TITLE
Issue #9

### PR DESCRIPTION
**Pull request by merrygobyebye**
## Description
Replace usage of `ext.postBuildExtras` with usage of `cdvPluginPostBuildExtras`.

## Related Issue
Issue #9

## Motivation and Context
This improves inter-compatibility with other Cordova plugins.

### CODE REVIEW

**Comment by cmartin81** [comment]
Please merge. It solved my issue regarding dependency errors

**Comment by chemerisuk** [comment]
Google recommends to apply this plugin in the bottom of grade file. That’s why I use postBuildExtras property.

Hopefully the project will be integrated into Cordova-android and this project become deprecated. Read https://github.com/apache/cordova-android/pull/438#discussion_r216195917

**Comment by merrygobyebye** [comment]
@chemerisuk, both `ext.postBuildExtras` and `cdvPluginPostBuildExtras` are run at the bottom of the gradle file. See https://github.com/apache/cordova-android/blob/e9750b5cabe70b1fc9abfad28fd1239d9b9415c2/bin/templates/project/app/build.gradle#L316-L324. 

As `cdvPluginPostBuildExtras` is an array, it can be used by many plugins. Each plugin simply adds its gradle code to this array. `ext.postBuildExtras` is only defined once, so it can only be used by one plugin. For example, if you have a Cordova project with this plugin and 
https://github.com/blakgeek/cordova-plugin-flurryanalytics, they both use `ext.postBuildExtras` (you can see its usage here: https://github.com/blakgeek/cordova-plugin-flurryanalytics/blob/master/src/android/plugin.gradle). Only the last plugin to be added will have its gradle code run in `ext.postBuildExtras`, so either this plugin or cordova-plugin-flurryanalytics would not work properly.

**Comment by chemerisuk** [comment]
It seems like https://github.com/apache/cordova-android/pull/438 was not merged into the next cordova-android release. Therefore we have to continue to use this plugin. 

Let's merge this PR and include changes into the next minor release.

**Pull request merged**
